language: java
install:
- cd stock_winner/
- chmod +x gradlew
- gradle assemble
deploy:
- cd stock_winner/
- chmod +x gradlew
  provider: heroku
  api_key:
    secure: f07de77b-58f7-47e7-9895-f4ee8a4595f7
  app: stock-winner
  on:
    repo: UnLow1/Stock-winner
